#!/usr/bin/env bash
# installing nginx in my server
sudo apt update
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'Nginx HTTPS'
sudo ufw allow 'Nginx Full
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i 's/listen [[:digit:]]\{2,\} default_server/listen 80 default_server/' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:[[:digit:]]\{2,\} default_server/listen [::]:80 default_server/' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen [[:digit:]]\{2,\} default_server/listen 80 default_server/' /etc/nginx/sites-enabled/default
sudosed -i 's/listen \[::\]:[[:digit:]]\{2,\} default_server/listen [::]:80 default_server/' /etc/nginx/sites-enabled/default
sudo service restart nginx

