#!/usr/bin/env bash
# installing nginx in my server
sudo apt update
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'Nginx HTTPS'
sudo ufw allow 'Nginx Full
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i 's/\tlisten [0-9].* default_server/\tlisten 80 default_server/' /etc/nginx/sites-enabled/default
sed -i 's/\tlisten \[::\]:[0-9].* default_server/\tlisten [::]:80 default_server/' /etc/nginx/sites-enabled/default
sed -i 's/\tlisten [0-9].* default_server/\tlisten 80 default_server/' /etc/nginx/sites-enabled/default
sed -i 's/\tlisten \[::\]:[0-9].* default_server/\tlisten [::]:80 default_server/' /etc/nginx/sites-enabled/default
sudo service nginx restart

