#!/usr/bin/env bash
# installing nginx in my server
sudo apt update
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'Nginx HTTPS'
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart

