#!/usr/bin/env bash
# redirecting path
# installing nginx first
./1-install_nginx_web_server
url = \troot \/var\/www\/html\n\trewrite \^\/redirect_me$ https:\/\/www\.youtube\.com\/watch?v=QH2-TGUlwu4 permanent;
sudo sed -i "s/root \/var\/www\/html;/$url/" /etc/nginx/site-available/default
sudo sed -i "s/root \/var\/www\/html;/$url/" /etc/nginx/site-enabled/default
sudo service nginx restart
