#!/usr/bin/env bash
# configing 404 error file
./3-redirection
sudo touch /usr/share/nginx/html/page_error_404.html
sudo chmod a+w /usr/share/nginx/html/page_error_404.html
sudo echo "Ceci n'est pas une page" > /usr/share/nginx/html/page_error_404.html
sudo sed -i '37i error_page 404 /page_error_404.html;\nlocation = /page_error_404.html {\nroot /usr/share/nginx/html; \ninternal;\n}\n' /etc/nginx/sites-enabled/default
sudo sed -i '37i error_page 404 /page_error_404.html;\nlocation = /page_error_404.html {\nroot /usr/share/nginx/html; \ninternal;\n}\n' /etc/nginx/sites-available/default
sudo service nginx restart
