#!/usr/bin/env bash
# a Bash script that configures a server and listening on port 80 of all the server’s active IPv4 IPs
sudo apt update
sudo apt-get install -y nginx
sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart

