#!/usr/bin/env bash
# Prints every minute and hour from 1-59 and 1-12, respectively

hours=0
min=1

while [ $hours -le 12 ]; do
	echo "Hour: $i"
	while [ $min -le 59 ]; do
		echo $min
		j=$((j+1))
	done
	min=$((1))
	hours=$((i+1))
done