#!/usr/bin/env bash
# Prints every minute and hour from 1-59 and 1-12, respectively

hours=0
min=1

while [ $hours -le 11 ]; do
	echo "Hour: $i"
	while [ $min -le 59 ]; do
		echo $min
		((min++))
	done
	min=1
	((hours++))	
done