#!/usr/bin/env bash
# displaying information about file

if [ -e school ]; then
echo "school file exists"
else
echo "school file does not exist"
exit 
fi
filename=school
 
if [ ! -s "${filename}" ]; then
echo "school file is empty"
else
echo "school file is not empty"
fi
if [ -f ${filename} ]; then
echo "school is a regular file"
fi